(function(root){
 'use strict';const C=AndreCourse,G=AndreCourseGrammar,P=AndreLearningPath,engine=SentenceGame.engine;
 const el=id=>document.getElementById(id),make=(tag,cls,text='')=>{const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;};
 let active=false;const trainer=make('section','grammar-rule-view');trainer.id='grammarTrainer';trainer.hidden=true;el('grammar').append(trainer);
 function button(label,fn,cls='study-button'){const b=make('button',cls,label);b.type='button';b.addEventListener('click',()=>{if(!b.disabled)fn();});return b;}
 function permitted(level){return level<engine.flow.frontier||level===engine.flow.frontier&&engine.wordsReady();}
 function overview(){if(active)return;const list=el('grammarList');list.replaceChildren();engine.syncProgress();
  for(const cefr of ['A1','A2','B1','B2']){const group=make('details','grammar-level-section');group.open=C.bandAt(engine.flow.level).cefr===cefr;const summary=make('summary','grammar-level-heading',cefr);group.append(summary);const rows=make('div','grammar-levels');
   for(const lesson of P.lessons.filter(l=>l.cefr===cefr)){const allowed=permitted(lesson.level),done=!!engine.flow.completed[lesson.level];const b=button('',()=>open(lesson.level),'grammar-level'+(lesson.level===engine.flow.level?' current':''));b.disabled=!allowed;b.dataset.learningLevel=lesson.level;
    b.append(make('strong','','Level '+lesson.level+(done?' ✓':'')),make('small','',lesson.title));b.setAttribute('aria-label','Level '+lesson.level+' · '+lesson.title+' · '+(done?'Gelernt':allowed?'Regel ansehen':'Gesperrt'));rows.append(b);}
   group.append(rows);list.append(group);
  }
 }
 function rule(e){const f=e.op?.after||{},text=e.text;
  if(e.op?.stage==='derivation')return (f.derivation==='with'?'Mit / ausgestattet mit: -lı, -li, -lu, -lü. Der letzte Vokal des Stamms entscheidet.':f.derivation==='without'?'Ohne: -sız, -siz, -suz, -süz. Der letzte Vokal des Stamms entscheidet.':'Nomen + (y)ken bedeutet „als / während“. Nach einem Vokal kommt y dazwischen.')+' Hier übst du '+text+'.';
  if(e.op?.stage==='case')return ({dative:'Richtung oder Ziel: -e / -a. Nach einem Vokal steht y dazwischen.',locative:'Ort: -de / -da; nach ç, f, h, k, p, s, ş, t steht t statt d.',ablative:'Herkunft: -den / -dan; nach ç, f, h, k, p, s, ş, t steht t statt d.',accusative:'Ein bestimmtes Objekt erhält -ı, -i, -u oder -ü. Nach einem Vokal steht y dazwischen.',genitive:'Besitzer: -(n)ın / -(n)in / -(n)un / -(n)ün. Das besessene Nomen bekommt zusätzlich eine Besitzendung.',instrumental:'Begleitung oder Mittel: -la / -le; nach einem Vokal -yla / -yle.'})[f.case]+' Hier übst du '+text+'.';
  if(e.op?.stage==='poss')return 'Die Besitzendung zeigt, wem etwas gehört. Hier: '+text+'. Danach kann eine Fallendung folgen.';
  if(e.op?.stage==='plural')return 'Mehrzahl: nach a, ı, o, u steht -lar; nach e, i, ö, ü steht -ler.';
  if(f.voice)return ({passive:'Die betroffene Sache wird zum Subjekt; wer handelt, muss nicht genannt werden.',reflexive:'Die Person handelt an sich selbst. Die Reflexivform wird mit dem Verb gelernt.',causative:'Jemand veranlasst eine Handlung. Wer sie ausführt und was betroffen ist, sind verschiedene Rollen.',reciprocal:'Mehrere Personen handeln miteinander.'})[f.voice]+' Hier übst du '+text+'.';
  if(f.compound)return (f.compound==='past'?'Die zusätzliche Vergangenheitsendung verlegt Handlung, Gewohnheit oder Zukunft in eine frühere Betrachtungszeit.':'Die zusätzliche -miş-Form zeigt, dass die Information gehört oder erschlossen wurde.')+' Hier übst du '+text+'.';
  if(f.ability)return 'Nach dem Verbstamm steht -(y)abil / -(y)ebil für „können“. Die verneinte Form bedeutet „nicht können“. Hier übst du '+text+'.';
  if(f.tense==='present')return 'Entferne -mak / -mek und ergänze '+text+'. '+(f.register==='colloquial'?'Alltagsform für A1/A2; bei Fragen bleibt die Person am Verb.':'Standardform ab B1; bei Fragen steht die Person in der Regel an mı / mi / mu / mü.');
  if(e.op?.stage==='predicate')return 'Eigenschaft oder Nomen + Personenendung. In Fragen steht mı / mi / mu / mü getrennt. Hier übst du '+text+'.';
  const tenseHelp={past:'Eine abgeschlossene Handlung: -DI + Person. Nach stimmlosen Konsonanten wird d zu t.',future:'Etwas Zukünftiges: -(y)AcAK + Person. Vor der ich-/wir-Endung wird k zu ğ.',aorist:'Eine Gewohnheit oder allgemeine Aussage. Die Aoristform gehört zum Verb und wird mitgelernt.',reported:'-mIş bezeichnet Gehörtes oder nachträglich Festgestelltes.',necessity:'-mAlI + Person drückt eine Notwendigkeit aus.',conditional:'Die Bedingung endet auf -sA + Person; danach folgt, was unter dieser Bedingung passiert.',optative:'-(y)AlIm ist ein Vorschlag für uns: „Lass uns …“.',imperative:'Die du-Aufforderung ist der Verbstamm ohne -mak / -mek.',ma:'-mA macht die Handlung zum Nomen. Besitz nennt die handelnde Person; danach kann ein Fall folgen.',dik:'-DIK + Besitzendung bildet einen abhängigen Inhalt. Vor einer vokalischen Endung wird k zu ğ.',acak:'-AcAK + Besitzendung bildet einen zukünftigen Inhalt; vor einer vokalischen Endung wird k zu ğ.',an:'-(y)An beschreibt, wer etwas tut. Der beschreibende Teil steht vor seinem Nomen.',ip:'-(y)Ip verbindet zwei Handlungen derselben Person; die Zeit steht am letzten Verb.',ince:'-(y)IncA bedeutet „sobald / als“.',arak:'-(y)ArAk zeigt, wie oder womit die andere Handlung geschieht.',madan:'-mAdAn bedeutet „ohne … zu“; zusammen mit önce „bevor“.',ken:'Aorist + ken verbindet gleichzeitig ablaufende Handlungen: „während“.',infinitive:'-mak / -mek bezeichnet die Tätigkeit ohne Zeit oder Person.'};
  if(e.op)return (tenseHelp[f.tense]||e.label)+ ' Hier übst du '+text+'.';
  const use=e.id.slice(4);
  if(use.startsWith('morph:')){const word=AndreWords.byId[use.split(':')[1]];return 'Bei '+word.tr+' verändert sich der Stamm vor dieser Endung: '+(word.vowelLoss||word.soften||word.vowelStem||word.progressiveStem)+'. Die Bedeutung bleibt gleich.';}
  if(use==='subject-person')return 'ben, sen, o und biz benennen die Person. Am Verb muss dieselbe Person stehen. Ein eindeutiges Personalpronomen darf auch fehlen.';
  if(use==='motion-target')return 'Das Ziel einer Bewegung erhält den Dativ: zum Haus / nach Hause heißt eve. Das Verb steht am Satzende.';
  if(use==='noun-compound')return 'Bei verbundenen Nomen trägt das zweite Nomen eine Besitzendung: protein + içecek → protein içeceği. Eine weitere Fallendung folgt danach.';
  if(use==='proper-name')return 'Bei Personennamen und solchen Eigennamen wird die Fallendung mit Apostroph angefügt: Mert → Mert\'e. Für die Vokalharmonie zählt die Aussprache.';
  return ({statement:'Im Türkischen steht die Aussage am Satzende. Bei „ist“ in der dritten Person ist oft keine eigene Endung nötig.',demonstrative:'bu bedeutet „dies / das“. Es steht vor dem, was du näher beschreibst.','negative-nominal':'değil verneint Eigenschaften und Nomen. Für ein verneintes Verb brauchst du dagegen die Verbendung.','question-ne':'ne fragt nach „was“.','icin:purpose':'Infinitiv + için nennt einen Zweck: etwas tun, um etwas zu erreichen.','icin:beneficiary':'Nomen + için bedeutet „für jemanden / etwas“.','icin:reason':'-DIK + Besitzendung + için nennt den Grund für die andere Handlung.','relative-subject':'Die Form auf -(y)An beschreibt das folgende Nomen: die Person oder Sache, die etwas tut.','relative-object':'Der beschreibende Satzteil steht vor dem Nomen. Seine Besitzendung nennt die handelnde Person.','content':'Der Inhalt wird zu einem Satzteil: -DIK oder -AcAK + Besitzendung, danach bei Bedarf die Fallendung.'})[use]||(/^(var|yok):/.test(use)?'var bedeutet „es gibt / vorhanden“, yok „es gibt nicht / fehlt“. Ort oder Besitzer stehen davor.':'Übersetze den ganzen Satz. Achte darauf, wie die bekannten Wörter die beiden Satzteile verbinden.');
 }

 function open(level=engine.flow.level){level=Number(level)||engine.flow.level;if(!permitted(level))return;const lesson=P.at(level);root.showView('grammar',null);active=true;el('grammarPanel').hidden=true;trainer.hidden=false;trainer.replaceChildren();
  trainer.append(button('← Grammatik',close,'learn-back'),make('h2','','Level '+level+' · '+lesson.cefr),make('h3','',lesson.title));
  const entries=lesson.targets.map(id=>G.byId[id]);if(!entries.length)trainer.append(make('p','','Verbinde die Regeln der bisherigen Lernschritte. Übe sie in verschiedenen Themen und in beiden Sprachen.'));
  for(const e of entries){trainer.append(make('p','grammar-rule-help',rule(e)));const example=e.examples.find(x=>x.task.requires.every(id=>engine.unlocked().has(id)));if(example){const card=make('div','study-solution');card.append(make('span','study-language','Türkisch'),make('strong','',example.task.answer),make('span','study-language','Deutsch'),make('strong','',example.task.de));trainer.append(card);}}
  trainer.append(make('p','','Zum Aufstieg: 2 Einführungen, danach alle 23 Themen in beide Richtungen. Mindestens 80 % direkt richtig; jede neue Form dreimal ohne Hilfe in jeder Richtung.'),button('Im Satzbau üben',()=>{close(false);root.showView('flashcards',null);},'study-button primary'));AndreMotion.enter(trainer);root.updateUnlockButtons();
 }
 function close(animate=true){const was=active;active=false;trainer.hidden=true;el('grammarPanel').hidden=false;overview();root.updateUnlockButtons();if(was&&animate)AndreMotion.enter(el('grammarPanel'));}
 root.GrammarTrainer={open,close,canUnlock:()=>false,get active(){return active;}};root.openGrammarTraining=open;root.refreshGrammarUI=overview;overview();root.updateUnlockButtons();
})(window);
