const {test}=require('node:test'),assert=require('node:assert/strict'),L=require('../lib/guided-learning'),P=require('../lib/learning-path'),W=require('../data/words'),G=require('../lib/course-grammar'),C=require('../lib/course'),I=require('../lib/interest-generator'),Prep=require('../lib/word-preparation'),V=require('../lib/word-pictures'),Editor=require('../lib/answer-editor');
function engine(){const map=new Map(),storage={getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)},e=new L.Engine({storage});return {e,map,storage};}
function prepare(e,map,level){e.flow.level=level;e.flow.frontier=level;e.syncProgress();map.set(L.UNLOCK,JSON.stringify(Object.fromEntries(P.wordIds(level).map(id=>[id,{toTurkish:true,toGerman:true}]))));}
function solve(e,cur){cur.tokens=cur.task.groups.flatMap(g=>g.slots.map((s,i)=>({...C.copy(s),id:g.id+i,group:g.id})));return e.check({answer:cur.task.de});}
test('160 fixed steps, familiar names, distinct Ben and ben, and explicit visuals',()=>{assert.equal(P.lessons.length,160);assert.equal(P.auto.has(W.byLemma.ben.id),false);assert.ok(P.auto.has(W.words.find(w=>w.properName&&w.tr==='Ben').id));for(const w of W.words.filter(w=>!P.auto.has(w.id)))assert.ok(V.mapped(w),w.tr);for(const l of P.lessons){assert.ok(l.words.every(id=>W.byId[id]&&!P.auto.has(id)));assert.equal(l.cefr,['A1','A2','B1','B2'][Math.floor((l.level-1)/40)]);}});
test('word learning gates whole groups, retains failed words and needs both typed directions',()=>{
 const map=new Map(),p=new Prep.Preparation({getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)}),ids=['ev','araba','köpek','masa'].map(w=>W.byLemma[w].id),known=new Set();
 let cur=p.next(ids,known);assert.equal(cur.phase,'spoken');assert.equal(p.spoken('nope').correct,false);
 while(ids.some(id=>!p.progress(id).spoken)){cur=p.next(ids,known);assert.equal(cur.phase,'spoken');p.spoken(W.byId[cur.id].tr);}
 cur=p.next(ids,known);assert.equal(cur.phase,'choice');const choices=p.choices(ids,V.key);assert.equal(choices.length,4);assert.ok(choices.every(w=>ids.includes(w.id)));assert.equal(new Set(choices.map(w=>w.tr)).size,4);
 while(ids.some(id=>!p.progress(id).choice)){cur=p.next(ids,known);assert.equal(cur.phase,'choice');p.choose(cur.id);}
 cur=p.next(ids,known);assert.equal(cur.phase,'typing');p.type('wrong');assert.equal(p.type('wrong').reveal,true);assert.equal(p.progress(cur.id).tr,false);const restored=new Prep.Preparation(p.storage);assert.equal(restored.state.current.reveal,true);p.state.current.done=true;cur=p.next(ids,known);assert.equal(p.type(W.byId[cur.id].tr).correct,true);assert.equal(p.progress(cur.id).de,false);
});
test('no rolled-r requirement and no confusion with a different known Turkish word',()=>{const {storage}=engine(),p=new Prep.Preparation(storage),id=W.byLemma.araba.id;p.next([id],new Set());assert.equal(p.spoken('aaba').correct,true);p.state.current=null;p.progress(id).spoken=false;p.next([id],new Set());assert.equal(p.spoken('ev').correct,false);});
test('failure drops once per round, preserves vocabulary/grammar and keeps the frontier',()=>{const {e,map}=engine();prepare(e,map,2);e.grammar.state.unlocked['use:statement']=true;const r=e.round();r.intro=2;for(const theme of I.themes)for(const direction of ['tr','de'])r.items.push({theme:theme.id,direction,direct:false});const before=e.unlocked().size,report=e.finishRound();assert.equal(report.pass,false);assert.equal(e.flow.level,1);assert.equal(e.flow.frontier,2);assert.equal(e.unlocked().size,before);assert.equal(e.grammar.state.unlocked['use:statement'],true);assert.equal(e.finishRound(),null);});
test('success requires topic coverage and three distinct applications in both directions',()=>{const {e,map}=engine();prepare(e,map,1);const r=e.round();r.intro=2;for(const theme of I.themes)for(const direction of ['tr','de'])r.items.push({theme:theme.id,direction,direct:true});assert.equal(e.finishRound(),null);for(const id of e.requirements())r.counts[id]={tr:['a','b','c'],de:['a','b','c']};assert.equal(e.finishRound().pass,true);assert.equal(e.flow.level,2);assert.equal(e.flow.frontier,2);assert.equal(e.grammar.state.unlocked['use:statement'],true);});
test('a prepared current rule is temporarily usable, but word unlocks alone do not level up',()=>{const {e,map}=engine();assert.equal(e.next(),null);prepare(e,map,1);assert.equal(e.flow.level,1);assert.equal(e.grammar.unlocked().has('use:statement'),false);assert.equal(e.practiceGrammar().has('use:statement'),true);const cur=e.next();assert.ok(cur);const report=solve(e,cur);assert.ok(report.correct);assert.equal(e.flow.level,1);assert.equal(e.round().items.length,0);assert.equal(e.round().intro,1);});
test('Unicode cursor edits within a sentence and respects limits',()=>{const cur={draft:'a😀b',caret:2};Editor.edit(cur,'ş');assert.equal(cur.draft,'a😀şb');Editor.edit(cur,'BACKSPACE');assert.equal(cur.draft,'a😀b');Editor.edit(cur,'Home');Editor.edit(cur,'İ');assert.equal(cur.draft,'İa😀b');Editor.edit(cur,'End');Editor.edit(cur,'z',4);assert.equal(cur.draft,'İa😀b');});
test('the final course remains free practice and future dictionary words do not reopen fixed packages',()=>{const {e,map}=engine();prepare(e,map,160);e.flow.finished=true;e.grammar.state.unlocked=Object.fromEntries(G.entries.map(g=>[g.id,true]));const cur=e.next();assert.equal(cur.free,true);const before=e.flow.level;assert.equal(e.check({unknown:true}).delta,0);assert.equal(e.flow.level,before);assert.equal(e.flow.finished,true);});
